# Generated by Django 2.2.5 on 2021-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='order',
            name='order_json',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
